// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClientConfig() {
  return window['go']['main']['App']['GetClientConfig']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveClientConfig(arg1) {
  return window['go']['main']['App']['SaveClientConfig'](arg1);
}

export function SetActiveVideoSource(arg1) {
  return window['go']['main']['App']['SetActiveVideoSource'](arg1);
}

export function SetMQTTHeroIdentity(arg1) {
  return window['go']['main']['App']['SetMQTTHeroIdentity'](arg1);
}

export function SetMQTTRobotIdentity(arg1) {
  return window['go']['main']['App']['SetMQTTRobotIdentity'](arg1);
}
