// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClientConfig():Promise<string>;

export function QuitApp():Promise<void>;

export function SaveClientConfig(arg1:string):Promise<void>;

export function SetActiveVideoSource(arg1:string):Promise<void>;

export function SetMQTTHeroIdentity(arg1:string):Promise<void>;

export function SetMQTTRobotIdentity(arg1:string):Promise<void>;
